### ISSUE TITLE
Navigate the command history mess with the date before the command prompt

### ISSUE THREAD

**Issue by Faury** [vitorjclima/CustomizingBashrc#2]
Navigating in the command history mess with  the date and the commands that were previously there.

zuser@Blah ~/directory (master) 
**[11:0ls -mtlrinit**

Please fix it.

**Comment by thiagocardoso1988** [comment]
There is something about the non-printable characters I've read about and I think this has something related to it. I'll check this out

**Comment by Faury** [comment]
The issue is no longer happening.
